Since setuptools 58.x, the use_2to3 was removed
This will break some package install such as jsmin:
```
Collecting jsmin>=2.2.2
  Downloading jsmin-2.2.2.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/xsdocs/envs/latest/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_6ebk9o3/jsmin_6a59d7cef8264cccabb9a86265ed6777/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_6ebk9o3/jsmin_6a59d7cef8264cccabb9a86265ed6777/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9dz8c8xo
         cwd: /tmp/pip-install-_6ebk9o3/jsmin_6a59d7cef8264cccabb9a86265ed6777/
    Complete output (1 lines):
    error in jsmin setup command: use_2to3 is invalid.
```